version: '3'

services:
  postgres:
    container_name: flask_db
    restart: always
    image: postgres:10
    environment:
      POSTGRES_USER: puser
      POSTGRES_PASSWORD: ppass
      POSTGRES_DB: pdatabase
    volumes:
      - ./pdata:/var/lib/postgresql/data

    ports:
    - "5432:5432"

  app:
    container_name: flask_app
    restart: always
    build: .
    volumes:
    - .:/app
    ports:
    - 5000:5000

volumes:
  pdata:
  app:
